docs/specification.md

Fix two doc links

---

crates/ddl-test/src/support/directives/lexer.rs
crates/ddl-test/src/support/directives/mod.rs
crates/ddl-test/src/support/directives/parser.rs
crates/ddl/src/concrete/grammar.lalrpop
crates/ddl/src/concrete/mod.rs
crates/ddl/src/elaborate/mod.rs

This was more trouble than it was worth! Keeping things simple for now!

Remove spanned string type

---

crates/ddl-test/src/support/mod.rs
crates/ddl/src/core/validate.rs
crates/ddl/src/delaborate.rs
crates/ddl/src/diagnostics.rs
crates/ddl/src/elaborate.rs
crates/ddl/src/lexer.rs
crates/ddl/src/lib.rs
crates/ddl/src/surface/delaborate.rs
crates/ddl/src/surface/elaborate.rs
crates/ddl/src/surface/grammar.lalrpop
crates/ddl/src/surface/mod.rs
docs/specification.md
docs/specification/elaboration.md
docs/specification/surface-syntax.md

This seems to be the terminology that [more people are using](https://twitter.com/heades/status/1170828909178511371). It also plays off 'core' in a nicer way.

Rename 'concrete' to 'surface'

---

crates/ddl/src/core/compile/rust/mod.rs
crates/ddl/src/core/validate.rs
crates/ddl/src/surface/elaborate.rs

Doing some cleanups in preparation for adding dependent records

Context simplifications

---

crates/ddl/src/binary/read.rs
tests/input/alias/pass_if_else_format_type.rs
tests/input/alias/pass_if_else_format_type_item.rs
tests/input/alias/pass_match_int_format_type.rs
tests/input/alias/pass_simple.rs
tests/input/struct/pass_empty.rs
tests/input/struct/pass_pair.rs
tests/input/struct/pass_singleton.rs

Clean ups for some things I missed in #202

Read context improvements

---

crates/ddl/src/core/compile/rust/diagnostics.rs
crates/ddl/src/core/compile/rust/mod.rs
crates/ddl/src/rust/mod.rs

Trying to clean up the compiler somewhat - it's been getting a tad unwieldy!

Compiler cleanups

---

CONTRIBUTING.md

This adds some more information about the contribution workflow, taking inspiration from the [Allsorts contributing guide](https://github.com/yeslogic/allsorts/blob/6a5566bb633d031e8c8352d082bedb6d9733dae2/CONTRIBUTING.md).

Add more details to the contributing guide

---

book/src/guide/first-format.md
book/src/index.md

As i find them, i'm fixing small typos and inconsistencies.

docs: Small fixes as i look through the book.

---

fathom-test/src/support/mod.rs

This makes things more consistent with the current module naming scheme

Cleanup inconsistent identifiers in tests

---

examples/edid.fathom
examples/gif.fathom
examples/icns.fathom
examples/ico.fathom
examples/opentype.fathom

Main branch renamed to `main` :hand: :fr: Reopening, but this is morally still #246 (see discussion there).

Add some aspirational examples

---

formats/opentype.fathom

Chipping away at implementing more parts of OpenType!

More work on OpenType format description

---

doc/README.md
doc/reference.md

This adds a reference level guide for the currently implemented features of Fathom.
I still haven't finished all the sections, so I'm posting this as a draft PR to show my progress.

Write some reference docs

---

fathom/src/surface/distillation.rs
fathom/src/surface/pretty.rs

Improve pretty printed output with better indentation, use of trailing separators, and distillation accuracy.

Improve pretty printing

---

fathom/src/surface/elaboration.rs

This is a refactoring in order to make defining the boolean primitives possible/easier as discussed in the chat. The naming is open to bike shedding/improvement, feel free to make suggestions.

Introduce RigidEnvBuilder for defining default env

---

fathom/src/core.rs
fathom/src/surface/distillation.rs

Remove BoolTrue and BoolFalse primitives

---

fathom/src/surface/elaboration.rs
fathom/src/surface/elaboration/reporting.rs
tests/fail/elaboration/array-literal-not-supported.snap
tests/fail/elaboration/mismatched-array-length/array16.snap
tests/fail/elaboration/mismatched-array-length/array32.snap
tests/fail/elaboration/mismatched-array-length/array64.snap
tests/fail/elaboration/mismatched-array-length/array8.snap
tests/fail/elaboration/numeric-literal/invalid.fathom
tests/fail/elaboration/numeric-literal/invalid.snap
tests/fail/elaboration/numeric-literal/mismatched-length.snap
tests/fail/elaboration/numeric-literal/not-supported.snap
tests/fail/elaboration/string-literal/not-supported.snap

Make some errors more descriptive.

More descriptive error messages

---

fathom/src/surface/elaboration.rs
fathom/src/surface/elaboration/reporting.rs
tests/succeed/hole/hole-0.snap
tests/succeed/hole/hole-1.snap

I tried a bunch of different variations on this but this is the only one that I could get to compile _and_ work. I'm not super happy with the result: it's verbose, requires temporary Vecs, and a new temporary type. I invite and welcome attempts to find a more pleasing implementation.

Include expression when hole solution is found

---

doc/background.md

This mentions some connections between our approach to format descriptions and universes in type theory. Considering it took me a bit to get my head around I think it could be worth documenting it.

Document some connections to type theory

---

fathom/src/core.rs
fathom/src/surface/distillation.rs

Some more cleanups to arrow distillation

Cleanups to arrow distillation

---

.github/workflows/ci.yml
fathom/src/alloc.rs
fathom/src/core.rs
fathom/src/core/binary.rs
fathom/src/core/semantics.rs
fathom/src/driver.rs
fathom/src/env.rs
fathom/src/lib.rs
fathom/src/source.rs
fathom/src/surface.rs
fathom/src/surface/elaboration.rs
fathom/src/surface/elaboration/order.rs
fathom/src/surface/elaboration/reporting.rs
fathom/src/surface/elaboration/unification.rs
fathom/src/surface/lexer.rs
fathom/src/surface/pretty.rs
fathom/tests/source_tests.rs

Thought it was about time I fixed these clippy lints.
Seemed to uncover a bunch of reasonable issues even the there are some lints I’m a bit wary of.

Fix clippy lints

---

.github/workflows/ci.yml
flake.nix

This adds a job for checking clippy lints on CI

Check clippy lints on CI

---

fathom/src/core/semantics.rs

I committed your idea from yesterday @brendanzab as I think it's an improvement.

Always return a function from prim_step

---

fathom/src/surface/elaboration.rs

I altered the literal parser methods on the elaboration context to take the literal constructors, which cleans up some of the multi-line match arms in the elaborator.

Improve readability of literal elaboration

---

fathom/src/core/semantics.rs

This adds some panicking methods to cleanup some of the variable handling in the semantics.

Cleanups to variable handling in semantics

---

fathom/src/core.rs
fathom/src/core/semantics.rs
fathom/src/surface/distillation.rs
fathom/src/surface/elaboration.rs
fathom/src/surface/elaboration/unification.rs
tests/succeed/equality.fathom
tests/succeed/equality.snap

Somewhere along the line we forgot to add a case for this.

Unify constant matches

---

fathom/Cargo.toml
fathom/src/core.rs
fathom/src/core/binary.rs
fathom/src/driver.rs
fathom/src/env.rs
fathom/src/source.rs
fathom/src/surface.rs
fathom/src/surface/elaboration.rs
fathom/src/surface/elaboration/reporting.rs
fathom/tests/source_tests.rs

Updating the minimum rust version to `1.62.0` triggered some more clippy lints

Apply clippy suggestions

---

fathom/src/core/pretty.rs

I was just using this and it looks like I missed some spaces.

Add some missing spaces to the core pretty printer

---

doc/roadmap.md
fathom/src/surface/distillation.rs
tests/succeed/equality.snap
tests/succeed/prelude.snap
tests/succeed/stress.snap

Generate fresh names for used `_` names during distillation.

Replace all used occurances of `_` with fresh names

---

fathom/src/core/pretty.rs

Apply the same fix from #483 to `core::pretty`

Fix exponential complexity in `core::pretty`
