yeslogic/fathom

- .travis.yml
Due to a Rust [version regression in `typed-arena`](https://github.com/SimonSapin/rust-typed-arena/issues/31) we can now only support Rust 1.36.  This adds a temporary minimum version of Rust 1.36, and allows failures for Rust 1.32 until this is resolved.
> Temporary fix for typed-arena version regression

- .travis.yml
Now that SimonSapin/rust-typed-arena#33 has been merged, we should now be able to compile on Rust 1.32 again.
> Revert typed-arena workaround

- .travis.yml
See the discussion at servo/string-cache#228.
> Bump minimum Rust to 1.36.0

- .travis.yml
The travis caches are currently between 5 and 10Gb and the build spends a lot of time (about 6 mins x 2) downloading and unpacking before the build and packing and uploading afterwards.
> Avoid caching the target directory during CI

- docs/specification/references.md
* Update the HarfBuzz links to use the latest repository. Since GitHub redirects the old <https://github.com/behdad/harfbuzz> to the new <https://github.com/harfbuzz/harfbuzz>, this is merely a nice-to-have.
* Fix the broken “a handy set of types and macros” link. The `hb-open-type-private.hh` file was split into multiple files and no longer exists. I've gleaned that the relevant change occurred in https://github.com/harfbuzz/harfbuzz/commit/92b1e025c639d006f55400bf68fc23bdeaa1c716. 🚧**Please verify that the new link points to the intended code.**
> Update and fix HarfBuzz links

- crates/ddl/src/binary/read.rs
- crates/ddl/src/core/compile/rust/mod.rs
- crates/ddl/src/core/grammar.lalrpop
- crates/ddl/src/core/mod.rs
- crates/ddl/src/core/semantics.rs
- crates/ddl/src/core/validate.rs
- crates/ddl/src/surface/delaborate.rs
- crates/ddl/src/surface/elaborate.rs
- tests/input/alias/pass_if_else_format_type_item.rs
- tests/input/alias/pass_match_int_format_type_item.rs
We now pass items through to the evaluator, allowing us to resolve aliases to the terms they point to. This mirrors the way that type aliases work in Rust. We might need to be careful about what happens when wrapper structs are generated in the Rust backend, but I’ll leave that to another day!
Closes #162.
> Make aliases transparent

- crates/ddl-test/src/support/mod.rs
- crates/ddl/src/core/mod.rs
- crates/ddl/src/core/pretty.rs
- crates/ddl/src/diagnostics.rs
- crates/ddl/src/surface/compile/doc/mod.rs
- crates/ddl/src/surface/delaborate.rs
- crates/ddl/src/surface/elaborate.rs
- crates/ddl/src/surface/grammar.lalrpop
- crates/ddl/src/surface/mod.rs
- crates/ddl/src/surface/pretty.rs
- tests/snapshots/alias/fail_ann_mismatch.html
- tests/snapshots/alias/pass_match_int_ann_type.core.ddl
- tests/snapshots/alias/pass_match_int_ann_type.html
This improves the pretty printing to insert parentheses only in the places where needed. This will become more important when we add more complicated syntax, like function application and arrows.
> Improve the quality of pretty printing

- crates/ddl-test-util/Cargo.toml
- crates/ddl-test-util/src/lib.rs
- crates/ddl-test/Cargo.toml
- crates/ddl-test/src/support/directives/lexer.rs
- crates/ddl-test/src/support/directives/mod.rs
- crates/ddl-test/src/support/directives/parser.rs
- crates/ddl-test/src/support/mod.rs
- crates/ddl/Cargo.toml
- crates/ddl/src/core.rs
- crates/ddl/src/core/compile/rust.rs
- crates/ddl/src/core/compile/rust/diagnostics.rs
- crates/ddl/src/core/grammar.lalrpop
- crates/ddl/src/core/semantics.rs
- crates/ddl/src/core/validate.rs
- crates/ddl/src/diagnostics.rs
- crates/ddl/src/lexer.rs
- crates/ddl/src/literal.rs
- crates/ddl/src/surface.rs
- crates/ddl/src/surface/compile/doc.rs
- crates/ddl/src/surface/delaborate.rs
- crates/ddl/src/surface/elaborate.rs
- crates/ddl/src/surface/grammar.lalrpop
- experiments/rust-prototype-v2/src/syntax/core.rs
- experiments/rust-prototype-v2/src/syntax/raw.rs
Switch to using the simpler types defined in `codespan_reporting`. I'm probably going to deprecate `codespan` ultimately, so this a step in the right direction I think?
> Use codespan-reporting only, removing codespan

- experiments/makam-spec/src/lang/core/semantics.makam
- experiments/makam-spec/src/lang/core/typing.makam
- experiments/makam-spec/src/pass/surface_to_core.makam
- experiments/makam-spec/test/lang/core/semantics.makam
- fathom-test/src/support/mod.rs
- fathom/src/diagnostics.rs
- fathom/src/lang.rs
- fathom/src/lang/core.rs
- fathom/src/lang/core/binary/read.rs
- fathom/src/lang/core/grammar.lalrpop
- fathom/src/lang/core/semantics.rs
- fathom/src/lang/core/typing.rs
- fathom/src/lang/surface.rs
- fathom/src/lang/surface/grammar.lalrpop
- fathom/src/lib.rs
- fathom/src/pass/core_to_pretty.rs
- fathom/src/pass/core_to_surface.rs
- fathom/src/pass/surface_to_core.rs
- fathom/src/pass/surface_to_doc.rs
- fathom/src/pass/surface_to_pretty.rs
- tests/input/alias/pass_format_array.rs
- tests/input/alias/pass_if_else_format_type.rs
- tests/input/alias/pass_if_else_format_type_item.rs
- tests/input/alias/pass_match_int_format_type.rs
- tests/input/alias/pass_match_int_format_type_item.rs
- tests/input/alias/pass_simple.rs
- tests/input/struct/pass_empty.rs
- tests/input/struct/pass_pair.rs
- tests/input/struct/pass_singleton.rs
Over the past few months I've learned even more about implementing languages thanks to my ongoing work on [pikelet's 'next' branch](https://github.com/pikelet-lang/pikelet/tree/next). Having them side-by-side makes it clear that Fathom needs a bit of TLC. Hoping to do this before @toothbrush and I get too stuck into collaborating, which might make changing this stuff a bit more challenging.
> Move some cleanups from Pikelet into Fathom

- book/src/background.md
- book/src/implementation/contributing.md
- book/src/reference/format-descriptions.md
- book/src/reference/sorts.md
- book/src/specification/textual-representation/concrete-syntax.md
These were discovered after a quick scan-through of the docs.
> Fix a few documentation typos

- experiments/makam-spec/src/lang/core/base.makam
- experiments/makam-spec/src/lang/core/semantics.makam
- experiments/makam-spec/src/lang/core/typing.makam
- experiments/makam-spec/src/lang/stratified.makam
- experiments/makam-spec/src/pass/core_to_stratified.makam
- experiments/makam-spec/src/pass/surface_to_core.makam
- experiments/makam-spec/test/lang/core/semantics.makam
- experiments/makam-spec/test/lang/core/typing.makam
- experiments/makam-spec/test/pass/surface_to_core.makam
This probably makes this a tad clearer, because you’d most likely expect `format_elim` to be doing induction over format descriptions, where as it's more a builtin function that does this induction over format descriptions internally.
> Rename format_elim to format_repr in makam spec

- .editorconfig
- .github/workflows/ci.yml
- book/.gitignore
- book/README.md
- book/book.toml
- book/index.js
- book/package.json
- book/src/reference/records.md
- book/theme/highlight.js
- package.json
- yarn.lock
I’ve tried using a patched version of highlight.js in the past, but it’s a pain to keep it up to date. Instead I’m using a version of highlight.js sorced from npm, rather than the minified version included in mdBook. This requires stubbing out the global `hljs` object in `theme/highlight.js` to avoid any method not found exceptions coming from mdBook’s generated book.js file. Ideally there’d be an easier way to do this in mdBook itself (see rust-lang/mdBook#657).
> Use custom syntax highlighting in book

- Cargo.toml
- fathom-cli/Cargo.toml
- fathom-cli/src/cli.rs
- fathom-cli/src/main.rs
I've grabbed the options as suggested in #239 by @mikeday, and put them into this simple configuration.  While the flags work pretty much as described in that issue, the output of `--help` leaves a lot to be desired and i'm not sure that [`structopt`](https://github.com/TeXitoi/structopt) actually can accommodate everything we want.
Things i'd still like to fix:
- Make it clear that `--format` and `--format-file` are mutually exclusive, instead of exploding if a user tries to specify both.
- Sensibly group the format- and output-related options in `--help`.  Currently they're just sorted alphabetically.
I don't want to waste too much time on this, i'll revisit it once this package has managed to integrate with `fathom` a little.
> First cut of laying out options

- fathom/src/lang/core/lexer.rs
- fathom/src/lang/surface/lexer.rs
These [were fixed](https://github.com/rust-analyzer/rust-analyzer/pull/6248) in rust-analyzer’s new TextMate grammar.
> Remove editor workarounds

- .github/workflows/ci.yml
- book/book.toml
We should adapt now that Github has [deprecated the old way of setting environment variables](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/).
Since i'm a pedant, i've also added quoting around shell arguments that could cause word-splitting.
Also killing a warning from Github Actions by explicitly setting Ubuntu version.
> Github Actions disables add_path: fix!

- fathom/src/lang.rs
- fathom/src/lang/core/grammar.lalrpop
- fathom/src/lang/core/lexer.rs
- fathom/src/lang/core/semantics.rs
- fathom/src/lang/core/typing.rs
- fathom/src/lang/surface/grammar.lalrpop
- fathom/src/lang/surface/lexer.rs
- fathom/src/literal.rs
- fathom/src/pass/surface_to_core.rs
- fathom/src/reporting.rs
Some assorted cleanups related to wrangling ASTs.
- adds a `Range` type that can be copied
- adds `Value::{try_global, try_item}` shortcut methods to clean up some pattern matching
This is implemented on-top of #248
> Tree wrangling cleanups

- fathom-test-util/src/lib.rs
- fathom/src/lang/core/binary.rs
- fathom/src/lang/core/binary/read.rs
- fathom/src/lang/core/semantics.rs
- tests/input/constant/pass_format_array.rs
- tests/input/constant/pass_if_else_format_type.rs
- tests/input/constant/pass_if_else_format_type_item.rs
- tests/input/constant/pass_match_int_format_type.rs
- tests/input/constant/pass_match_int_format_type_item.rs
- tests/input/constant/pass_simple.rs
- tests/input/struct/pass_empty.rs
- tests/input/struct/pass_pair.rs
- tests/input/struct/pass_singleton.rs
Thanks to the addition of array terms (#265) and struct terms (#248) we are now able to represent all format representations in the host language. This lets us remove `lang::core::binary::Term`, and return values from the interpreted binary reader instead, making it easier to implement dependent parsing in the future (see #244).
> Return values from binary reader

- fathom/src/lang/core/binary/read.rs
- tests/input/constant/pass_format_array.rs
- tests/input/constant/pass_if_else_format_type.rs
- tests/input/constant/pass_if_else_format_type_item.rs
- tests/input/constant/pass_match_int_format_type.rs
- tests/input/constant/pass_match_int_format_type_item.rs
- tests/input/constant/pass_simple.rs
- tests/input/struct/dependent_fields.rs
- tests/input/struct/pass_empty.rs
- tests/input/struct/pass_pair.rs
- tests/input/struct/pass_singleton.rs
This changes the binary interpreter's API to be a bit easier to work with. Instead of supplying a module when reading an item from a `ReadScope`, the module is loaded up when the interpreter context is initially constructed. The `ReadScope` is then passed as an argument to `Context::read_item`.
> Binary interpreter API improvements

- .github/workflows/ci.yml
This was broken in lalrpop/lalrpop#564. See https://github.com/lalrpop/lalrpop/issues/580 for more information.
> Bump MSRV to 1.43

- fathom/src/lang/core.rs
- fathom/src/pass/surface_to_core.rs
Found a simpler way of doing looking up a type annotation based on its name, by storing variable names alongside their type annotations as opposed to in a separate `Vec`.
> Remove level substitutions in elaborator

- book/src/specification/textual-representation/concrete-syntax.md
- book/src/specification/textual-representation/lexical-syntax.md
This simplifies the grammars in the specification by removing the formatting. This should be easier to update. In the future we could use a MDBook plugin to format the grammars nicely in HTML.
I’ve also updated the grammars to match the current surface language (some things were missing or had changed).
> Cleanup grammars in specification

- .github/workflows/ci.yml
Bumping due to im depending on a new version of sized-chunks. The error we got on Rust 1.43 was:
```
error[E0658]: `if` is not allowed in a `const fn`
Error:    --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/sized-chunks-0.6.3/src/inline_array/mod.rs:108:5
|
108 | /     if element_size == 0 {
109 | |         usize::MAX
110 | |     } else {
111 | |         (host_size - header_size) / element_size
112 | |     }
| |_____^
|
= note: see issue #49146 <https://github.com/rust-lang/rust/issues/49146> for more information
```
> Bump MSRV to Rust 1.46+

- fathom-test/src/support/directives/lexer.rs
- fathom-test/src/support/directives/mod.rs
- fathom-test/src/support/directives/parser.rs
- fathom-test/src/support/mod.rs
- fathom/src/driver.rs
- fathom/src/lang.rs
- fathom/src/lang/core.rs
- fathom/src/lang/core/binary/read.rs
- fathom/src/lang/core/grammar.lalrpop
- fathom/src/lang/core/lexer.rs
- fathom/src/lang/core/semantics.rs
- fathom/src/lang/core/typing.rs
- fathom/src/lang/surface.rs
- fathom/src/lang/surface/grammar.lalrpop
- fathom/src/lang/surface/lexer.rs
- fathom/src/literal.rs
- fathom/src/pass/core_to_surface.rs
- fathom/src/pass/surface_to_core.rs
- fathom/src/reporting.rs
Instead of storing the file id in the module, we instead store them in source locations wherever they are needed in the AST. This means the ASTs will consume more memory, but it simplifies the compiler a great deal. We can always optimise this later by compressing source locations or using a location sidetable.
> Rework how we manage file ids in the AST.

- LICENSE
- fathom/Cargo.toml
This restores the license file to the root of the repository, and switches the author field to YesLogic. Somehow I missed these in #296.
> Metadata fixes

- fathom/src/core.rs
- fathom/src/core/binary.rs
- fathom/src/core/semantics.rs
- fathom/src/surface.rs
- fathom/src/surface/distillation.rs
- fathom/src/surface/elaboration.rs
- fathom/src/surface/elaboration/unification.rs
- fathom/src/surface/grammar.lalrpop
- fathom/src/surface/lexer.rs
- fathom/src/surface/pretty.rs
- tests/succeed/format-overlap/dependent.fathom
- tests/succeed/format-overlap/numbers.fathom
This implements a format comprised of a dependent sequence of overlapping formats. This allows later information to affect how past information is parsed, which could be useful for defining the tricky mutual recursion found in the font tables in OpenType.
> Implement overlap formats

- flake.lock
- flake.nix
For some reason I wasn't getting any backtraces on `aarch64-darwin` when developing using nixpkgs. Updating the lockfile seemed to fix this. For convenience I also set `RUST_BACKTRACE=1` in dev shells by default.
> Fix backtraces for nixpkgs+aarch64-darwin

- doc/reference.md
- fathom/src/core.rs
- fathom/src/core/binary.rs
- fathom/src/core/semantics.rs
- fathom/src/driver.rs
- fathom/src/surface/distillation.rs
- fathom/src/surface/elaboration.rs
- fathom/src/surface/pretty.rs
- formats/opentype.fathom
- tests/succeed/format-repr/primitives.fathom
- tests/succeed/primitives.fathom
The link formats could be simplified to a single `link` format if we allowed for limited arithmetic on positions. For now I just have a bunch of link formats that take a position and an offset:
- `Ref : Type -> Type`
- `link8 : Pos -> U8 -> Format -> Format`
- `link16 : Pos -> U16 -> Format -> Format`
- `link32 : Pos -> U32 -> Format -> Format`
- `link64 : Pos -> U64 -> Format -> Format`
Todo:
> Link formats

- formats/opentype.fathom
This PR describes the remaining OpenType `cmap` sub-tables as much as possible. I've tested all tables against real fonts, comparing read values to [ttf-explorer](https://github.com/RazrFalcon/ttf-explorer) except for format 13, which I couldn't find a font for.
> Opentype cmap sub-table formats

- fathom/src/core/binary.rs
- fathom/src/driver.rs
- fathom/src/surface/pretty.rs
This allows multiple linked formats to occupy the same position in the binary file.
Currently this just renders the different formats as a list corresponding to each position in the CLI. In the future I'd want to explore a different way of displaying these - perhaps something like `pos : Repr format = ...` or `pos : format = ...` (if we add format -> repr coercions) - but this would require glued evaluation of [top-level items](https://github.com/yeslogic/fathom/issues/318) to avoid swamping users with massive format descriptions.
> Allow different formats at the same ref position

- .vscode/extensions.json
- .vscode/settings.json
- doc/reference.md
- fathom/src/core.rs
- fathom/src/core/binary.rs
- fathom/src/core/semantics.rs
- fathom/src/surface/elaboration.rs
- formats/opentype.fathom
- formats/opentype.snap
- tests/succeed/format-repr/primitives.fathom
- tests/succeed/format-repr/primitives.snap
- tests/succeed/primitives.fathom
- tests/succeed/primitives.snap
This implements a number of primitives for adding unsigned numbers to positions:
- `pos_add_u8 : Pos -> U8 -> Pos`
- `pos_add_u16 : Pos -> U16 -> Pos`
- `pos_add_u32 : Pos -> U32 -> Pos`
- `pos_add_u64 : Pos -> U64 -> Pos`
This means that we can simplify link formats down to a single primitive:
- `link : Pos -> Format -> Format`
At the moment these operations will get 'stuck' during evaluation if they overflow, which will ultimately lead to a parse error. We might need to consider a different approach in the future but I think this is fine for now.
> Simplify link formats with position addition operations

- doc/reference.md
- fathom/src/core.rs
- fathom/src/core/binary.rs
- fathom/src/core/semantics.rs
- fathom/src/surface/elaboration.rs
- tests/succeed/format-deref/simple.fathom
- tests/succeed/format-deref/simple.snap
- tests/succeed/format-repr/primitives.fathom
- tests/succeed/format-repr/primitives.snap
- tests/succeed/primitives.fathom
- tests/succeed/primitives.snap
This is take two of implementing deref formats, after #320 . This alters references to now be indexed with the format description of the linked data (as opposed to the representation type):
- `Ref : Format -> Type`
The following format description allows for parsing those references eagerly:
- `deref : fun (f : Format) -> Ref f -> Format`
The number of calls to `ConversionContext::is_equal` in order to look up references in the cache is a bit of a worry, but I have some ideas about how to improve this if it ever becomes a problem, which I've noted down in comments.
Closes #320
> Implement deref formats

- fathom/src/driver.rs
- fathom/src/surface.rs
- fathom/src/surface/grammar.lalrpop
- fathom/src/surface/lexer.rs
- tests/fail/parse/error-recovery.fathom
- tests/fail/parse/error-recovery.snap
This allows for further parsing to take place after a syntax error is encountered. For more information check out the [LALRPOP book's chapter on error recovery](https://lalrpop.github.io/lalrpop/tutorial/008_error_recovery.html).
> Wire up error recovery in the parser.

- fathom/src/surface/elaboration.rs
This simplifies the `RigidEnvBuilder` by constructing terms then evaluating them, rather than constructing values directly.
> Simplify RigidEnvBuilder

- fathom/src/core.rs
- fathom/src/core/binary.rs
- fathom/src/core/semantics.rs
- fathom/src/surface.rs
- fathom/src/surface/distillation.rs
- fathom/src/surface/elaboration.rs
- fathom/src/surface/elaboration/reporting.rs
- fathom/src/surface/elaboration/unification.rs
- fathom/src/surface/grammar.lalrpop
- fathom/src/surface/pretty.rs
- tests/succeed/prelude.fathom
- tests/succeed/prelude.snap
Currently I use terminology from [natural deduction](https://ncatlab.org/nlab/show/natural+deduction) to inform the names of the variants in the core language. This has turned out to be a bit intimidating and a source of confusion. The consistency between the names seems to also get in the way of understanding.
In the interest of making it a bit easier to understand and work on Fathom, this PR switches to more familiar names. We can tweak this further down the line, but I hope it helps!
Let me know your thoughts on this.
> Rename variants in the core language

- formats/opentype.fathom
- formats/opentype.snap
I swear these couldn’t be solved back when I was first implementing #310, but something must be different now. It could have been I had an actual type error at the time, but I was prodding around in the dark, lacking the nice errors we have now!
> Use placeholders when applying `deref` in opentype

- doc/reference.md
- fathom/src/core/semantics.rs
- fathom/src/surface.rs
- fathom/src/surface/distillation.rs
- fathom/src/surface/elaboration.rs
- fathom/src/surface/grammar.lalrpop
- fathom/src/surface/lexer.rs
- fathom/src/surface/pretty.rs
- formats/edid.fathom
- formats/edid.snap
- formats/icns.fathom
- formats/icns.snap
- formats/opentype.fathom
- formats/opentype.snap
- tests/succeed/format-cond/simple.fathom
- tests/succeed/format-cond/simple.snap
- tests/succeed/format-overlap/field-refinements.fathom
- tests/succeed/format-overlap/field-refinements.snap
- tests/succeed/format-record/field-refinements.fathom
- tests/succeed/format-record/field-refinements.snap
This implements some short-hand sugar for refining fields with predicates. Closes #368.
```
{
magic <- u32be where u32_eq magic "icns",
⋮
}
```
These are turned into conditional formats during elaboration. I went with calling them ’field refinements’ as if felt like ‘conditional fields’ could be interpreted as being optional. Another name for them could be ‘field guards’, perhaps.
I also found a bug in the implementation of `Repr` for conditional fields in the process!
> Implement `where` sugar for refined fields

- doc/reference.md
- fathom/src/surface.rs
- fathom/src/surface/distillation.rs
- fathom/src/surface/elaboration.rs
- fathom/src/surface/grammar.lalrpop
- fathom/src/surface/pretty.rs
- formats/opentype.fathom
- formats/opentype.snap
- tests/fail/parse/error-recovery.snap
- tests/succeed/format-record/computed-fields.fathom
- tests/succeed/format-record/computed-fields.snap
This implements some shorthand syntax for adding pure computations into a record format. For example:
```fathom
{
/// 2 × seg_count.
seg_count_x2 <- u16be,
/// Number of contiguous ranges of character codes
let seg_count = u16_div seg_count_x2 2,
//  ▲
//  └─── the value computed for `seg_count` will be
//       available for use in subsequent fields
⋮
start_code <- array16 seg_count u16be,
id_delta <- array16 seg_count s16be,
//                  ▲
//                  └──── `seg_count` is used here
}
```
This is translated to a `succeed` format during elaboration.
> Add surface syntax for computed fields

- fathom/src/core/binary.rs
- fathom/src/driver.rs
- formats/data/edid/invalid/wrong-magic.snap
As discussed this is an attempt to make the read errors a bit nicer.
Some of the copy probably still has room for improvement/expanding. Also I wasn't sure about `InvalidFormat`. Is that an error that can be readily user triggered or is not supposed to be encountered in practice? If that latter then it can probably be moved to an `UnexpectedError`, at least for now.
> Make read errors slightly better

- fathom/src/core/binary.rs
- fathom/src/driver.rs
I ran into this error when I was working on adding `GPOS` to the OpenType definition and wished there was more info in it. I've added the bad offset to the error, which may or may not actually be useful. I've also moved it out of the `bug` reporting branch when reporting errors since it can be triggered with bad data or bad format description.
> Provide more information in SetOffsetOutsideBuffer error

- fathom/src/core/binary.rs
Noticed this doing some other research. Prior to this change the `Vec` was allocated every time, even if the entry was already populated.
> Avoid allocating Vec every time we add to reference cache

- fathom/src/core.rs
- fathom/src/core/binary.rs
- fathom/src/core/semantics.rs
- fathom/src/driver.rs
- fathom/src/lib.rs
- fathom/src/source.rs
- fathom/src/surface/distillation.rs
- fathom/src/surface/elaboration.rs
- fathom/src/surface/elaboration/reporting.rs
- fathom/src/surface/elaboration/unification.rs
- formats/data/edid/invalid/wrong-magic.snap
- formats/unwrap-none.fathom
- formats/unwrap-none.snap
- tests/cmd/fathom-data.md
This PR adds source location information to `core::Term` and `Value` so that this information can flow from the surface language through the core language and back out. This allows some errors to be much more helpful.
This is a large change but I tried to keep the commits focussed on a single `Term` or `Value` variant so the history should be quite readable. There are a number of `FIXME`, `TODO` comments and a few references to a `Span::fixme` method left. Most of them are questions that I want to discuss to determine the right approach to resolve them.
I initially added spans to `Value` directly but this made it difficult when reusing a shared value instance (since they are ref-counted). For example, when encountering a `fail` format the value is the shared fail instance in the …
> Track source locations in core::Term and Values

- .github/workflows/ci.yml
- fathom/Cargo.toml
- flake.lock
- flake.nix
The PR reduces the number of Rust toolchains we test against on CI. This was a holdover from my habits during pre-1.0 Rust where we were encouraged to test _all the versions_. Hopefully Github’s error de-duplication will improve in the future (see https://github.com/actions/runner/issues/504).
I also took the time to clean up the `flake.nix` file. It skips the packaging for now and just loads a Rust development environment. This is used on CI to load Rust instead of [actions-rs](https://github.com/actions-rs/) which appears to be dormant. This might be controversial, but it seemed decently clean and decreases the amount of setup stuck in CI land. We can always switch to another approach in the future though, as Fathom’s use case is pretty simple.
I also added the minimum supported rust …
> CI improvements and cleanups to flake.nix

- fathom/src/core.rs
There were a couple mistakes in the implementation of `contains_free`, this fixes them!
> Fix binding of distilled terms

- fathom/src/core/semantics.rs
- fathom/src/surface/elaboration.rs
Sometimes rustfmt gets a little excited with formatting, which has a negative impact on the readability of the code. To get around this we can either adjust the code to suit, or just use `#[rustfmt::skip]` to disable it in these cases.
> Clean up some formatting in match expressions

- fathom/src/core.rs
- fathom/src/core/binary.rs
- fathom/src/core/semantics.rs
- fathom/src/driver.rs
- fathom/src/env.rs
- fathom/src/surface/elaboration.rs
- fathom/src/surface/elaboration/unification.rs
This has been bugging me for a while, not sure what you think.
It’s probably a little less confusing to call these ‘environments’ as they are more related to evaluation, although to be honest the difference between ‘contexts’ and ‘environments’ is sometimes a tad… context dependent!
The rename reduces verbosity slightly in some cases which is a nice win for readability as well, I think.
> Rename environment structs in semantics

- doc/reference.md
As mentioned in https://github.com/yeslogic/fathom/pull/378#pullrequestreview-1035200218 the binary operators weren't mentioned in the reference, now they are :)
> Add bin ops to the reference

- fathom/src/core/semantics.rs
- fathom/src/source.rs
- fathom/src/surface/distillation.rs
- fathom/src/surface/elaboration.rs
Addressed some stuff I came across after the addition of spans. I’ve computed spans in some places in the elaborated terms. I also added a by-value conversion on byte ranges to make things a little cleaner in places, and cached some commonly used values to increase sharing (see the commit comment for more details).
> Span related cleanups

- fathom/src/surface.rs
- fathom/src/surface/elaboration.rs
- tests/succeed/match/check-const-1.snap
- tests/succeed/match/check-const-2.snap
- tests/succeed/match/check-const-bool.snap
- tests/succeed/match/check-const-redundant.snap
- tests/succeed/match/synth-const-1.snap
- tests/succeed/match/synth-const-2.snap
Apologies for the large diff! This builds upon #396, doing a bunch of cleanups related to the checking of patterns and elaboration of pattern matching. While our approach to pattern matching is still pretty naive (and that’s ok!), it was hard for me to understand and was somewhat embarrassing to look at, so I’ve tried to untangle it, reducing the number of parameters passed (keeping clippy happy) and splitting it into methods with more comments.
> Cleanups to pattern matching elaboration

- fathom/src/surface/elaboration/unification.rs
- tests/succeed/record-type/generic-pair.fathom
- tests/succeed/record-type/generic-pair.snap
- tests/succeed/record-type/generic-tiple.fathom
- tests/succeed/record-type/generic-tiple.snap
The cause of the bug was in the implementation of renaming record telescopes: we were pushing variables onto the local environment while traversing the telescope, rather than onto the partial renaming (cf `rename_closure`)
Fixes #408
> Fix issue #408

- .vscode/extensions.json
VSCode allows you to list recommended project-specific extensions in `.vscode/extensions.json`. This will prompt VSCode users to install the listed extensions the first time they load the project. This should make it slightly easier for new contributors who use VSCode to stick to the project's editing style.
> Recommend the `EditorConfig` extension for VSCode users

- fathom/src/core.rs
- fathom/src/core/semantics.rs
- fathom/src/surface/distillation.rs
- fathom/src/surface/elaboration.rs
- fathom/src/surface/elaboration/unification.rs
- tests/succeed/equality.snap
- tests/succeed/match/check-const-1.snap
- tests/succeed/match/check-const-2.snap
- tests/succeed/match/check-const-redundant.snap
- tests/succeed/match/synth-const-1.snap
- tests/succeed/match/synth-const-2.snap
At the moment, we throw away the name of the binder when elaborating pattern matches to `ConstMatch` with a default branch
eg
```fathom
match x {
0 => 1,
y => y,
}
```
elaborates to 
```fathom
match x {
0 => 1,
_ => _,
}
```
This patch preserves the name of the binding, making the elaborated core more readable
> Preserve name of default branch in `core::Term::ConstMatch`

- fathom/src/core.rs
- fathom/src/core/prim.rs
- fathom/src/core/semantics.rs
- fathom/src/driver.rs
- fathom/src/lib.rs
- fathom/src/source.rs
- fathom/src/surface.rs
- fathom/src/surface/distillation.rs
- fathom/src/surface/elaboration.rs
- fathom/src/surface/elaboration/order.rs
- fathom/src/surface/elaboration/reporting.rs
- fathom/src/surface/elaboration/unification.rs
- fathom/src/surface/grammar.lalrpop
- fathom/src/surface/pretty.rs
Some tweaks to the distillation of tuples:
- parses the field labels as opposed to pretty printing then checking for equality
- only checks for type dependencies if the fields of a record look like a tuple
> Some tweaks to tuple distillation

- fathom/src/source.rs
- fathom/src/surface/distillation.rs
- fathom/src/surface/elaboration.rs
- tests/succeed/tuple/generic-pair.fathom
- tests/succeed/tuple/generic-pair.snap
- tests/succeed/tuple/generic-triple.fathom
- tests/succeed/tuple/generic-triple.snap
- The issue was in distillation: we didn't push labels while distilling dependent tuples.
- Fixed a bug in the caching of tuple labels: `get_tuple_label` would not grow the `tuple_labels` vector, so `tuple_labels` would always be empty! This didn't affect correctness, but it did mean there was no performance improvement. 
- Added `get_tuple_labels` for getting a whole slice of tuple labels at once, and used it to optimize the implementation of `is_tuple_labels` 
Fixes #421
> Fix issue #421

- fathom/src/surface/elaboration/unification.rs
These new bindings were unnecessary. Leftover from when renaming used a separate arena?
> Remove useless copies

- fathom/src/surface/distillation.rs
- fathom/src/surface/elaboration.rs
`item_env.names` is already populated by elaboration, so we don't need to push item names onto the environment while distilling.
> Remove unecessary `push_item` from distillation

- fathom/src/surface/elaboration.rs
- fathom/src/surface/elaboration/reporting.rs
- tests/cmd/fathom-data.md
- tests/fail/elaboration/boolean-literal/type-mismatch.snap
- tests/fail/elaboration/unification/mismatch/arrow-body-type.snap
- tests/fail/elaboration/unification/mismatch/arrow-both.snap
- tests/fail/elaboration/unification/mismatch/arrow-param-type.snap
- tests/fail/elaboration/unification/mismatch/fun-literal-body-expr.snap
- tests/fail/elaboration/unification/mismatch/fun-literal-param-ann.snap
- tests/fail/elaboration/unification/mismatch/fun-type-body-type.snap
- tests/fail/elaboration/unification/mismatch/fun-type-both.snap
- tests/fail/elaboration/unification/mismatch/fun-type-param-type.snap
- tests/fail/elaboration/unification/mismatch/match-equation-body-exprs.snap
- tests/fail/elaboration/unification/mismatch/record-literal-singleton.snap
- tests/fail/elaboration/unification/mismatch/record-type-singleton.snap
- tests/fail/parse/error-recovery.snap
The ordering of the "expected" and "found" types when reporting a type mismatch was the wrong way around.
```fathom
false : U32
```
would produce 
```text
type mismatch, expected `Bool`, found `U32`
```
the correct order is
```text
type mismatch, expected `U32`, found `Bool`
```
> Fix ordering of `expected` and `found` types in elaboration::convert

- Cargo.lock
- fathom/Cargo.toml
- fathom/src/surface.rs
- fathom/src/surface/distillation.rs
- fathom/src/surface/elaboration.rs
- fathom/src/surface/elaboration/order.rs
- fathom/src/surface/grammar.lalrpop
- fathom/src/surface/pretty.rs
I opened a PR against LALRPOP to lex raw identifiers properly: https://github.com/lalrpop/lalrpop/pull/698. If it is accepted, we can use raw identifiers in our `grammar.lalrpop`.
> Use raw identifiers in LALRPOP grammar

- fathom/tests/source_tests.rs
- tests/fail/elaboration/item-cycle.fathom
- tests/fail/elaboration/item-cycle.snap
Allows the `TestMode` for test files to be overridden by `//~ mode = "module"` or `//~ mode = "term"` comments
> Allow `TestMode` to be set per-file by config comments

- fathom/src/core.rs
- fathom/src/core/semantics.rs
- fathom/src/driver.rs
- fathom/src/files.rs
- fathom/src/lib.rs
- fathom/src/main.rs
- fathom/src/source.rs
- fathom/src/surface.rs
- fathom/src/surface/elaboration.rs
- fathom/src/surface/elaboration/reporting.rs
- fathom/src/surface/grammar.lalrpop
- fathom/src/surface/lexer.rs
By using `u32` instead of `usize` for `BytePos`, and `NonZeroU32` instead of `usize` for `FileId`, we can significantly reduce the size of `ByteRange` and `Span`. This also reduces the size of types that carry `ByteRange` or `Span`:
- `source::ByteRange`: 24 bytes to 12 bytes
- `source::Span`: 24 bytes to 12 byes
- `surface::Term<ByteRange>`: 80 bytes to 56 bytes
- `surface::Pattern<ByteRange>`: 32 bytes to 16 bytes
- `core::Term`: 72 bytes to 56 bytes
- `semantics::Value`: 80 bytes to 72 bytes
- `elaboration::CheckedPattern`: 40 bytes to 32 bytes
> Reduce size of `ByteRange` and `Span`

- doc/reference.md
- fathom/src/core/pretty.rs
- fathom/src/surface.rs
- fathom/src/surface/lexer.rs
- fathom/src/surface/pretty.rs
- tests/succeed/raw-identifiers.fathom
- tests/succeed/raw-identifiers.snap
Allow keywords to be used as identifiers by prefixing them with `r#`, as in Rust (eg `r#let`)
> Lex raw identifiers

- doc/roadmap.md
- fathom/src/core.rs
- fathom/src/core/binary.rs
- fathom/src/core/pretty.rs
- fathom/src/core/prim.rs
- fathom/src/core/semantics.rs
- fathom/src/surface.rs
- fathom/src/surface/distillation.rs
- fathom/src/surface/elaboration.rs
- fathom/src/surface/elaboration/order.rs
- fathom/src/surface/elaboration/reporting.rs
- fathom/src/surface/elaboration/unification.rs
- fathom/src/surface/grammar.lalrpop
- fathom/src/surface/lexer.rs
- fathom/src/surface/pretty.rs
- tests/fail/elaboration/implicit-args/app-plicity-mismatch.fathom
- tests/fail/elaboration/implicit-args/app-plicity-mismatch.snap
- tests/fail/elaboration/implicit-args/unexpected-argument.fathom
- tests/fail/elaboration/implicit-args/unexpected-argument.snap
- tests/succeed/implicit-args/generalize.fathom
- tests/succeed/implicit-args/generalize.snap
- tests/succeed/implicit-args/insert-args.fathom
- tests/succeed/implicit-args/insert-args.snap
- tests/succeed/implicit-args/specialize.fathom
- tests/succeed/implicit-args/specialize.snap
Implement implicit arguments in the style of [elaboration zoo](https://github.com/AndrasKovacs/elaboration-zoo/tree/master/04-implicit-args).
- Implicit function types: `@A -> A` and `fun (@A : Type) -> A`
- Implicit function literals: `fun @x => x`
- Implicit function applications: `id @Bool`
- When synthesizing an explicit function application, insert implicit function applications for each implicit argument in the head type
- When checking a term against an implicit function type, insert implicit function applications for each implicit argument in the expected type
- When checking an explicit function literal against an implicit function type, wrap the checked term in an implicit function literal
I find it intuitive to think of inserting implicit applications as **specializing** the …
> Implicit args

- doc/reference.md
- fathom/src/core.rs
- fathom/src/core/prim.rs
- tests/succeed/primitives.fathom
- tests/succeed/primitives.snap
Felt we should have this for completeness, though of course it should be impossible to use.
> Add `absurd`, the eliminator for `Void`

- fathom/tests/source_tests.rs
This should make it a little easier understand failing tests
> Improve command printing in test failures

- fathom/src/alloc.rs
- fathom/src/core.rs
- fathom/src/core/binary.rs
- fathom/src/core/prim.rs
- fathom/src/core/semantics.rs
- fathom/src/driver.rs
- fathom/src/env.rs
- fathom/src/files.rs
- fathom/src/source.rs
- fathom/src/surface/distillation.rs
- fathom/src/surface/elaboration.rs
- fathom/src/surface/elaboration/order.rs
- fathom/src/surface/elaboration/reporting.rs
- fathom/src/surface/pretty.rs
- fathom/tests/source_tests.rs
- rustfmt.toml
`rustfmt` can wrap comments at 80 characters per line, but the feature must be enabled in `rustfmt.toml`
> Wrap comments at 80 characters

- doc/reference.md
- fathom/src/core/binary.rs
- fathom/src/core/prim.rs
- formats/opentype.fathom
- formats/opentype.snap
- formats/unwrap-none.fathom
- formats/unwrap-none.snap
- tests/succeed/format-deref/simple.fathom
- tests/succeed/format-deref/simple.snap
- tests/succeed/format-repr/primitives.fathom
- tests/succeed/primitives.fathom
- tests/succeed/primitives.snap
This uses implicit parameters to clean up some functions in the opentype format description, and updates the primitives to make use of implicit parameters.
> Use implicit parameters in primitives and opentype format

- fathom/src/surface/lexer.rs
- tests/fail/parse/unclosed-block-comment.snap
This uses Logos’ [lexer modes](https://github.com/maciejhirsz/logos/blob/51c1f8c1bca990758e05c5600becc6d9c10bd6e4/tests/tests/lexer_modes.rs) to parse block comments.
> Use lexer modes to parse block comments

- .github/workflows/ci.yml
- doc/reference.md
- fathom/src/core/pretty.rs
- fathom/src/surface.rs
- fathom/src/surface/distillation.rs
- fathom/src/surface/elaboration.rs
- fathom/src/surface/elaboration/order.rs
- fathom/src/surface/grammar.lalrpop
- fathom/src/surface/pretty.rs
Some cleanups to the implementation of implicit functions that were added in #439. I’ve broken the dependency on `core::Plicity` in the surface syntax, adjusted some names, and cleaned up the insertion of implicit arguments somewhat (inspired by [elaboration-zoo’s implementation](https://github.com/AndrasKovacs/elaboration-zoo/blob/master/04-implicit-args/Elaboration.hs)).
> Implicit function cleanups

- .github/workflows/ci.yml
- fathom/src/surface/distillation.rs
When developing using the stable toolchain this comment was being autoformatted.
> Fix stable vs. nightly comment formatting

- fathom/src/core/pretty.rs
- fathom/src/driver.rs
- fathom/src/files.rs
- fathom/src/source.rs
- fathom/src/surface.rs
- fathom/src/surface/elaboration.rs
- fathom/src/surface/elaboration/reporting.rs
- fathom/src/surface/grammar.lalrpop
- fathom/src/surface/lexer.rs
Replaces `FileRange` (`ByteRange` + `FileId`) with `ByteRange` in all surface AST types produced by parsing and consumed by elaboration. This shaves 8 bytes off each of `surface::Term` and `surface::Pattern`, and only makes elaboration slightly more complicated, so ought to be a good performance win.
* `surface::Term<ByteRange>`: 56 bytes to 48 bytes
* `surface::Pattern<ByteRange>`: 16 bytes to 12 bytes
> Use `ByteRange` instead of `FileRange` in surface AST

- fathom/src/surface/distillation.rs
- tests/succeed/distillation/fresh-names.fathom
- tests/succeed/distillation/fresh-names.snap
Noticed that the item names weren’t being checked during fresh name generation.
> Avoid item names

- fathom/src/surface/distillation.rs
- fathom/tests/source_tests.rs
- tests/fail/elaboration/unsolved/fun-literal-param-type.fathom
- tests/fail/elaboration/unsolved/fun-literal-param-type.snap
- tests/fail/elaboration/unsolved/fun-literal-placeholder-body-type.fathom
- tests/fail/elaboration/unsolved/fun-literal-placeholder-body-type.snap
- tests/fail/elaboration/unsolved/hole-ann.fathom
- tests/fail/elaboration/unsolved/hole-ann.snap
- tests/fail/elaboration/unsolved/hole.fathom
- tests/fail/elaboration/unsolved/hole.snap
- tests/fail/elaboration/unsolved/placeholder-ann.fathom
- tests/fail/elaboration/unsolved/placeholder-ann.snap
- tests/fail/elaboration/unsolved/placeholder.fathom
- tests/fail/elaboration/unsolved/placeholder.snap
Distills `core::Term::MetaVar` to `surface::Term::Name`, where the name is of the form `?{level}`. Since metavariables are global per module, we don't need to generate fresh names.
> Distill metavariables to named terms

- fathom/src/surface/elaboration.rs
- formats/opentype.snap
- tests/succeed/equality.snap
- tests/succeed/format-cond/simple.snap
- tests/succeed/format-overlap/dependent.snap
- tests/succeed/format-overlap/field-refinements.snap
- tests/succeed/format-overlap/numbers.snap
- tests/succeed/format-record/computed-fields.snap
- tests/succeed/format-record/field-refinements.snap
- tests/succeed/format-repr/pair-dependent.snap
- tests/succeed/format-repr/primitives.snap
- tests/succeed/format-repr/record.snap
- tests/succeed/format-repr/unit-literal.snap
- tests/succeed/let/id-type.snap
- tests/succeed/prelude.snap
- tests/succeed/primitive-ops.snap
- tests/succeed/record-type/generic-point.snap
- tests/succeed/record-type/generic-singleton.snap
- tests/succeed/stress.snap
- tests/succeed/tuple/check-term.snap
This reduces some bloat in the elaboration output
> Avoid unnecessary quotation in elaboration

- doc/reference.md
- fathom/src/surface/elaboration.rs
- formats/opentype.fathom
- tests/succeed/format-repr/coercions.fathom
- tests/succeed/format-repr/coercions.snap
This PR adds implicit coercions from format descriptions into their representation types during elaboration, removing the need to explicitly call `Repr` in most cases. This would _almost_ bring us full circle back to when I was trying to use subtyping in Fathom, but now the subtyping would be kept out of the core language, greatly reducing the confusing complications that resulted from conflating types and format descriptions. 
Introducing this style of coercive subtyping during elaboration is also not entirely unheard of either: it is a common addition for elaborators to type theories with Tarski-style universes, which seem to have [a connection](https://github.com/yeslogic/fathom/blob/main/doc/background.md#format-descriptions-as-universes) to our approach to format descriptions.
By …
> Coerce format descriptions into representation types

- fathom/src/surface/elaboration/unification.rs
Encountered this while writing my own unifier (https://github.com/Kmeakin/pion/blob/master/crates/pion-core/src/elab/unify.rs#L415). `try_fold` is short circuiting (will return early on the first `Err`), while `fold` is not.
> Use `Iterator::try_fold` instead of `fold` when renaming terms

- fathom/src/driver.rs
- fathom/src/main.rs
- fathom/src/source.rs
- fathom/src/surface.rs
- fathom/src/surface/lexer.rs
Adds `ProgramSource`, a wrapper around `String` which guarantees the length is `<= u32::MAX`. Allows us to remove the `assert` from `tokens`.
> Introduce a smart constructor around `String` for input sources

- Cargo.lock
- fathom/Cargo.toml
- fathom/src/alloc.rs
Update `scoped-arena` from `0.3.0` to `0.4.1`. This allows us to use the new `to_scope_many_with` method when creating a `SliceVec`
> Update `scoped-arena` from `0.3.0` to `0.4.1`

- Cargo.lock
- fathom/Cargo.toml
- fathom/src/alloc.rs
- Rename `next_index` to `len`
- Rename `max_len` to `capacity`
- Add accessor fns `len()`, `capacity()` and `is_full()`
- Panic with an informative message when trying to push onto a full `SliceVec`
> Slicevec cleanup

- fathom/src/source.rs
- fathom/src/surface.rs
`get_or_intern` panics when trying to intern more than 2^16 strings. 2^32 strings should be enough for anyone (said only slightly ironically)
> Use `SymbolU32` instead of `SymbolU16`

- fathom/src/surface.rs
- fathom/src/surface/elaboration.rs
- fathom/src/surface/elaboration/order.rs
- fathom/src/surface/grammar.lalrpop
- fathom/src/surface/pretty.rs
- tests/fail/elaboration/non-exhaustive-patterns/match-check.snap
- tests/fail/elaboration/non-exhaustive-patterns/match-synth.snap
This would allow us to pretty print the user's input exactly in the future (eg if we want a `fathom fmt` command). Would also allow us to move the precedence logic from `surface::pretty` to `core::distillation`
> Make parenthesized terms explicit in the surface AST

- fathom/src/core/semantics.rs
- fathom/src/driver.rs
- fathom/src/env.rs
- fathom/src/main.rs
- fathom/src/surface/distillation.rs
- fathom/src/surface/elaboration.rs
- fathom/src/surface/elaboration/unification.rs
- fathom/tests/source_tests.rs
- tests/cmd/fathom-norm.md
- tests/cmd/fathom.md
- tests/succeed/implicit-args/specialize.fathom
- tests/succeed/numeric-literal/style-conflict.fathom
- tests/succeed/numeric-literal/style-preserve-binary.fathom
- tests/succeed/numeric-literal/style-propagate-binary.fathom
- tests/succeed/numeric-literal/style-propagate-hex.fathom
We alternated between the [American `-ize` and British/Commonwealth `-ise`](https://en.wikipedia.org/wiki/American_and_British_English_spelling_differences#-ise,_-ize_(-isation,_-ization)) spelling inconsistently. I propose we standardize on the American spelling, in line with the Rust standard library documentation. [RFC 1574](https://github.com/rust-lang/rfcs/blob/master/text/1574-more-api-documentation-conventions.md) states:
> All documentation for the standard library is standardized on American English, with regards to spelling, grammar, and punctuation conventions. Language changes over time, so this doesn’t mean that there is always a correct answer to every grammar question, but there is often some kind of formal consensus.
> Replace all spellings of `-ise` with `-ize`

- fathom/Cargo.toml
- fathom/src/surface.rs
- flake.lock
Rust version `1.67` includes [an improvement to packing of structs and enums](https://releases.rs/docs/1.67.0/). This saves us 8 bytes on the size of `surface::Term<ByteRange>`.
Took the liberty of removing the tests for the size of `surface::Term<FileRange>` and `surface::Pattern<FileRange>` since we don't use them anymore.
> Bump to rust v1.67

- Cargo.toml
- fathom/src/surface/pretty.rs
- tests/cmd/fathom-data.md
Fixes very high heap utilization when rendering `surface` AST to `Doc` for pretty printing.
Problem was in `surface::pretty::sequence`, in particular the use of `FlatAlt`. `FlatAlt` requires allocating two AST nodes, one for the single line situation and one for the multi line situation. When used recursively, this will lead to exponential space and time complexity! Fortunately, we can push `FlatAlt` down into the leaves: it is only necessary when deciding whether to emit a separator (eg `,`) or `nil` at the end of the item in the list.
> Optimise `surface::pretty`

- fathom/src/alloc.rs
- fathom/src/core.rs
- fathom/src/core/binary.rs
- fathom/src/files.rs
- fathom/src/source.rs
- fathom/src/surface/elaboration/order.rs
- fathom/src/surface/pretty.rs
- fathom/tests/source_tests.rs
Use explicit type names in place of `Self` where possible. Dual to https://github.com/yeslogic/fathom/pull/480
> Use explicit type names in place of `Self` where possible

- fathom/src/surface/distillation.rs
Miscellaneous cleanups/refactors of `surface::distillation`:
* Replace the mutually recursive `check` and `synth` functions with a single `term` function. Now all logic is contained in one single function, and is IMO easier to understand.
* Boolean patterns were erroneously distilled to name patterns instead of boolean patterns in the surface syntax
* Avoid allocating an intermediate `Vec` when distilling a function application to a binop
> Cleanup distillation

- doc/reference.md
- fathom/src/surface.rs
- fathom/src/surface/distillation.rs
- fathom/src/surface/elaboration.rs
- fathom/src/surface/elaboration/order.rs
- fathom/src/surface/grammar.lalrpop
- fathom/src/surface/pretty.rs
- tests/succeed/record-field-shorthand.fathom
- tests/succeed/record-field-shorthand.snap
Adds syntax sugar for record fields: `{x, y, z}` is equivalent to `{ x = x, y = y, z = z }`. This is called [Struct field init shorthand](https://doc.rust-lang.org/reference/expressions/struct-expr.html#struct-field-init-shorthand) in Rust, and [record puns](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/record_puns.html) in Haskell
> Record field shorthands

- fathom/src/surface.rs
- fathom/src/surface/distillation.rs
- fathom/src/surface/elaboration.rs
- fathom/src/surface/elaboration/reporting.rs
In an attempt to address #488, this reduces some of the gymnasics we’ve needed to do whenever we want to pretty print something. We achieve this by cloning the name environment as opposed to taking it by mutable reference when constructing a distillation environment.
This means we can no longer reuse the existing allocation when temporarily pushing local names, but I think the savings we got from this was probably minor, and the increase in clarity is worth it.
> Make it easier to distill/pretty print values

- fathom/src/env.rs
Using `usize` means we don't have to worry about overflow: rust containers cannot contain more than `isize::MAX` bytes, so it is impossible for a `usize` derived from the length of a container to overflow (the max number of elements a container can have is therefore `isize::MAX / std::mem::size_of<T>`, which will always be less than `usize::MAX`).
This shouldn't have any performance impact:
* Operations on `usize` should always be at least as fast as operations on `u16`, since `usize` is the platform's native word type
* No size increases in any types that we track with tests was detected
* We don't do any operations over slices of vars, so there won't be any penalties due to more frequent cache misses or lower vectorization factors.
> Use `usize` instead of `u16` for vars
